name: Release Orchestration


# TODO: Tag and branch
# TODO: insure we can only release from privileged branches/tags
# TODO: watch for releasing the same version more than once

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: "Workflow test user input"
        type: string
        required: true
        default: "test input default value"

env:
  PYTHON_VERSION: "3.13"

jobs:
  test:
    name: "Prerelease Test"
    uses: ./.github/workflows/test.yml
  package:
    name: "Build Release Artifacts"
    uses: ./.github/workflows/release-build.yml
    needs: test
  publish:
    name: "Publish Release Artifacts"
    uses: ./.github/workflows/release-publish.yml
    needs: package
