name: Build Release Artifacts

on:
  workflow_dispatch:
  workflow_call:
  #workflow_run:
  #  workflows: ["Release Trigger"]
  #  types: ["completed"]
  #  branches:
  #    - 'releases/**'
  #    - 'main'
  #    - 'carl/**'  # FIXME: Remove.  This is for testing/development.
  #     if: ${{ github.event.workflow_run.conclusion == 'success' }}

env:
  PYTHON_VERSION: "3.13"

jobs:
  build-wheel:
    name: Build Wheel packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare common Python build environment
        uses: ./.github/actions/python-common-setup
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: 'Nox: Build Wheel'
        run: |
          nox -s build_wheel
      - name: Save Artifacts - Wheel
        uses: actions/upload-artifact@v4
        with:
          name: planet-auth-wheel
          path: dist/planet_auth*.whl
      - name: Save Artifacts - Source Package
        uses: actions/upload-artifact@v4
        with:
          name: planet-auth-src-targz
          path: dist/planet_auth*.tar.gz

  build-docs:
    name: Build MKDocs Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare common Python build environment
        uses: ./.github/actions/python-common-setup
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: 'Nox: Build MKDocs'
        run: |
          nox -s mkdocs_build

  release-pypi:
    name: Release package to PyPi
    runs-on: ubuntu-latest
    needs: build-wheel
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare common Python build environment
        uses: ./.github/actions/python-common-setup
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Download Wheel Package
        uses: actions/download-artifact@v4
        with:
          name: planet-auth-wheel
      - name: Download Source Package
        uses: actions/download-artifact@v4
        with:
          name: planet-auth-src-targz
      - name: 'Test Debug step'
        run: |
          ls -la dist
          false
      - name: 'Nox: Publish to PyPi'
        run: |
          nox -s release_pypi

  release-readthedocs:
    name: Release documentation to readthedocs.com
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare common Python build environment
        uses: ./.github/actions/python-common-setup
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: 'Nox: Publish to ReadTheDocs'
        run: |
          nox -s release_readthedocs
