name: Publish Release

# FIXME: How can I restrict actually publishing a release to specific users/tags/branches?

on:
  workflow_call:
  #workflow_run:
  #  workflows: ["Release Trigger"]
  #  types: ["completed"]
  #  branches:
  #    - 'releases/**'
  #    - 'main'
  #    - 'carl/**'  # FIXME: Remove.  This is for testing/development.
  #     if: ${{ github.event.workflow_run.conclusion == 'success' }}

env:
  PYTHON_VERSION: "3.13"

jobs:
  release-pypi:
    name: Release package to PyPi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare common Python build environment
        uses: ./.github/actions/python-common-setup
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Download Wheel Package
        uses: actions/download-artifact@v4
        with:
          name: planet-auth-wheel
          # github-token: ${{ secrets.GH_PAT }}
          # repository: '${{ github.repository }}'
          # run-id: '${{ github.run_id }}'
          path: dist
      - name: Download Source Package
        uses: actions/download-artifact@v4
        with:
          name: planet-auth-src-targz
          # github-token: ${{ secrets.GH_PAT }}
          # repository: '${{ github.repository }}'
          # run-id: '${{ github.run_id }}'
          path: dist
      - name: 'Nox: Publish to PyPi'
        run: |
          nox -s release_pypi

  release-readthedocs:
    name: Release documentation to readthedocs.com
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare common Python build environment
        uses: ./.github/actions/python-common-setup
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Download Built Documentations
        uses: actions/download-artifact@v4
        with:
          name: planet-auth-mkdocs-site
          # github-token: ${{ secrets.GH_PAT }}
          # repository: '${{ github.repository }}'
          # run-id: '${{ github.run_id }}'
          path: site
      - name: 'Nox: Publish to ReadTheDocs'
        run: |
          nox -s release_readthedocs
