name: Build Release Artifacts

# FIXME: How can I restrict actually publishing a release to specific users/tags/branches?  (Could someone call this workflow from a rogue branch?)

on:
  workflow_dispatch:
  workflow_call:
  #workflow_run:
  #  workflows: ["Release Trigger"]
  #  types: ["completed"]
  #  branches:
  #    - 'releases/**'
  #    - 'main'
  #    - 'carl/**'  # FIXME: Remove.  This is for testing/development.
  #     if: ${{ github.event.workflow_run.conclusion == 'success' }}

env:
  PYTHON_VERSION: "3.13"

jobs:
  build-wheel:
    name: Build Wheel packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare common Python build environment
        uses: ./.github/actions/python-common-setup
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: 'Nox: Build Wheel'
        run: |
          nox -s build_wheel
      - name: Save Artifacts - Wheel
        uses: actions/upload-artifact@v4
        with:
          name: planet-auth-wheel
          path: dist/planet_auth*.whl
      - name: Save Artifacts - Source Package
        uses: actions/upload-artifact@v4
        with:
          name: planet-auth-src-targz
          path: dist/planet_auth*.tar.gz

  build-docs:
    name: Build MKDocs Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare common Python build environment
        uses: ./.github/actions/python-common-setup
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: 'Nox: MKDocs Build'
        run: |
          nox -s mkdocs_build
      - name: Save Artifacts - MkDocs
        uses: actions/upload-artifact@v4
        with:
          name: planet-auth-mkdocs-site
          path: site/**

  dummy-fail:
    name: Dummy fail
    runs-on: ubuntu-latest
    steps:
      - name: 'False'
        run: |
          /bin/false
