name: Release Trigger

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: "Workflow test user input"
        type: string
        required: true
        default: "test input value"

env:
  PYTHON_VERSION: "3.13"

# TODO: Tag and branch

jobs:
  test:
    name: "Pre-relase Test"
    uses: ./.github/workflows/test.yml
  package:
    name: "Package"
    uses: ./.github/workflows/release-build.yml
    needs: test
  foo-1:
    name: "Foo 1"
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: '/bin/true'
        run: |
          /bin/true
  foo-2:
    name: "Foo 2"
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: '/bin/false'
        run: |
          /bin/false
  foo-3:
    name: "Foo 3"
    runs-on: ubuntu-latest
    needs: foo-2
    steps:
      - name: '/bin/true'
        run: |
          /bin/true
  # publish:
  #   name: "Publish"
  #   uses: ./.github/workflows/release-publish.yml
  #   needs: package
