name: Publish Release

on:
  workflow_call:
    secrets:
      PYPI_API_TOKEN:
      PYPI_API_TOKEN_TEST:

env:
  PYTHON_VERSION: "3.13"

jobs:
  release-checkpoint:
    name: Final Release Checkpoint
    runs-on: ubuntu-latest
    # environment: staging
    # TODO: ask the user to approve the release
    # TODO: Add a check some place to refuse to publish an already published version.
    #      (do this when generating the build number, I think. Move the tag here, too? But I like tagging after tests pass to minimize noise.)
    # TODO: Gate actual prod deployment on a manual approval to bonk.
    # TODO: can/should we automatically bump the branch invariant version number after a release?
    # FIXME: do we need the code?
    # FIXME: Checkbox/select/approave each release artifact?
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare common Python build environment
        uses: ./.github/actions/python-build-env-setup
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Record Release Tag
        run: |
          false
          git tag -a -m "comment" "build-release-tag"
          git tag -a -m "comment" "final-release-tag" (if release)
          git push origin "build-release-tag"
          git push origin "final-release-tag" (if release)
  release-pypi-test:
    name: Release package to PyPi (Test)
    needs: release-checkpoint
    runs-on: ubuntu-latest
    # environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare common Python build environment
        uses: ./.github/actions/python-build-env-setup
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Download Wheel Package
        uses: actions/download-artifact@v4
        with:
          name: planet-auth-wheel
          # github-token: ${{ secrets.GH_PAT }}
          # repository: '${{ github.repository }}'
          # run-id: '${{ github.run_id }}'
          path: dist
      - name: Download Source Package
        uses: actions/download-artifact@v4
        with:
          name: planet-auth-src-targz
          # github-token: ${{ secrets.GH_PAT }}
          # repository: '${{ github.repository }}'
          # run-id: '${{ github.run_id }}'
          path: dist
      - name: 'Nox: Publish to PyPi'
        env:
          NOX_PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN_TEST }}
        # TODO: re-enable. Disabled for pipeline development - nox -s pkg_publish_pypi_test
        run: |
          false

  #release-pypi-production:
  #  name: Release package to PyPi (Production)
  #  TODO: Copy-pasta-replace the above when all settled.

  release-readthedocs:
    name: Release documentation to readthedocs.com
    needs: release-checkpoint
    runs-on: ubuntu-latest
    # environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare common Python build environment
        uses: ./.github/actions/python-build-env-setup
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Download Built Documentations
        uses: actions/download-artifact@v4
        with:
          name: planet-auth-mkdocs-site
          # github-token: ${{ secrets.GH_PAT }}
          # repository: '${{ github.repository }}'
          # run-id: '${{ github.run_id }}'
          path: site
      - name: 'Nox: Publish to ReadTheDocs'
        run: |
          nox -s mkdocs_publish_readthedocs
